### ISSUE TITLE
GeneralTopics.md feedback on questions

### ISSUE THREAD

**Issue by charlottebrf** [WeRockTech/DiscussionTopics#2]
| Section     | Details     WeRockTech                         |
| --GeneralTopics.md--------- | ------------------------------------ |
| Type        |  Idea / Feedback /
| Title       |    GeneralTopics.md feedback on questions                                  |
| Description |   change worst mistake question to : "Are there any things you wish you'd done **differently** during different stages of your career? If so, what and why?" . Feels less negative & more constructive in terms of helping other people see & think about things they wish they'd done differently.                          |
| Screenshot  | Include?  No                    |

**Comment by eddiejaoude** [comment]
_Reformatted above_

| Section | Details |
| --- | --- |
| Type | Idea / Feedback |
| Title | GeneralTopics.md feedback on questions |
| Description | change worst mistake question to : "Are there any things you wish you'd done **differently** during different stages of your career? If so, what and why?" . Feels less negative & more constructive in terms of helping other people see & think about things they wish they'd done differently. |
| Screenshot | No |

**Comment by eddiejaoude** [comment]
Thanks, that is a great idea & much better! 👍

**Comment by eddiejaoude** [comment]
Updated
