### ISSUE TITLE
WomenRockTechSeries.md

### ISSUE THREAD

**Issue by charlottebrf** [WeRockTech/DiscussionTopics#3]
| Section     | Details                              |
| --WeRockTech--------- | ---WomenRockTechSeries.md--------------------------------- |
| Type        |  Feedback  |
| Title       |     WomenRockTechSeries.md feedback                                 |
| Description |    Reword: "What advice would you give to someone especially Women who want to go but are unsure?"-- add in "...who want to go into tech but are unsure?"                                 |
| Screenshot  | Include? Yes 
![screen shot 2016-04-05 at 23 03 06](https://cloud.githubusercontent.com/assets/16884984/14299503/b66accca-fb82-11e5-9e82-6242e644ea2a.png)
                  |

**Comment by eddiejaoude** [comment]
_Reformatted above_

| Section | Details |
| --- | --- |
| Type | Feedback |
| Title | WomenRockTechSeries.md feedback |
| Description | Reword: "What advice would you give to someone especially Women who want to go but are unsure?"-- add in "...who want to go into tech but are unsure?" |
| Screenshot | Yes |

**Comment by eddiejaoude** [comment]
Will do, thanks! 👍

**Comment by eddiejaoude** [comment]
Updated
