### ISSUE TITLE
WomenRockTechSeries.md #3

### ISSUE THREAD

**Issue by charlottebrf** [WeRockTech/DiscussionTopics#4]
| Section     | Details                              |
| -WeRockTech---------- | ---WomenRockTechSeries.md #3--------------------------------- |
| Type        | Feedback 
| Title       |    WomenRockTechSeries.md #3 feedback 2                                  |
| Description |    Do we need more info here on what WomenRockTechSeries is? Is it exclusively Ones to Watch or will it be other women also? Think this needs more info. Will you have draft questions here?                                  |
| Screenshot  | Include? No                    |

**Comment by eddiejaoude** [comment]
_Reformatted above_

| Section | Details |
| --- | --- |
| Type | Feedback |
| Title | WomenRockTechSeries.md #3 feedback 2 |
| Description | Do we need more info here on what WomenRockTechSeries is? Is it exclusively Ones to Watch or will it be other women also? Think this needs more info. Will you have draft questions here? |
| Screenshot | No |

**Comment by eddiejaoude** [comment]
Yes you are right, I definitely need to add more information here and make it more clear! The CF:G OnesToWatch are exclusive to [WomenToWatch](https://github.com/WeRockTech/DiscussionTopics/blob/master/WomenToWatchSeries.md) Series. I can rename this to make it more clear? What about **CF:G OnesToWatch 2016** Series?

**Comment by eddiejaoude** [comment]
Or still have **WomenToWatch** Series but in the description have it clear that it is from the **CF:G**'s list of **OnesToWatch2016**?

**Comment by eddiejaoude** [comment]
Updated
