### ISSUE TITLE
CF: G Ones to Watch Discussion Topics

### ISSUE THREAD

**Issue by charlottebrf** [WeRockTech/DiscussionTopics#5]
| Section     | Details                              |
| --CF: G Ones to Watch--------- | -----Discussion Topics------------------------------- |
| Type        |  Feedback /r |
| Title       |     CF: G Ones to Watch                                 |Discussion Topics
| Description |      Where do we put in the more tailored questions for each speaker? I think outside of the general questions we have (which are good for all) were you planning on drafting like 3 specific questions for each person?                                |
| Screenshot  | Include? Yes 
![screen shot 2016-04-18 at 15 49 40](https://cloud.githubusercontent.com/assets/16884984/14608393/728991b2-057d-11e6-9619-678b7af7511d.png)
                  |

**Comment by eddiejaoude** [comment]
Reformatted above question

| Section | Details |
| --- | --- |
| CF: G Ones to Watch | Discussion Topics |
| Type | Feedback |
| Title | CF: G Ones to Watch |
| Description | Where do we put in the more tailored questions for each speaker? I think outside of the general questions we have (which are good for all) were you planning on drafting like 3 specific questions for each person? |
| Screenshot | Yes |

**Comment by eddiejaoude** [comment]
Q.

> Where do we put in the more tailored questions for each speaker? I think outside of the general questions we have (which are good for all) were you planning on drafting like 3 specific questions for each person?

A.
Each person will have a file where the specific questions can be added, I have created a place holder as people confirm. Feel free to add questions as you think of them, we can reformat later https://github.com/WeRockTech/DiscussionTopics/tree/master/CustomTopics/WomenToWatch2016

**Comment by charlottebrf** [comment]
Ah ok that's what I thought I just wasn't sure- that's great!

On 18 April 2016 at 15:57, Eddie Jaoude notifications@github.com wrote:

> Q.
> 
> Where do we put in the more tailored questions for each speaker? I think
> outside of the general questions we have (which are good for all) were you
> planning on drafting like 3 specific questions for each person?
> 
> A.
> Each person will have a file where the specific questions can be added, I
> have created a place holder as people confirm. Feel free to add questions
> as you think of them, we can reformat later
> https://github.com/WeRockTech/DiscussionTopics/tree/master/CustomTopics/WomenToWatch2016
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/WeRockTech/DiscussionTopics/issues/5#issuecomment-211415962

## 

---

_Charlotte Fereday_

Programmes Manager @codefirstgirls

Tweeting & retweeting @charlottebrf

*Mainly: Tech/Education/Hispanic studies *

**Comment by eddiejaoude** [comment]
Don't worry, its GitHub, everything is versioned, change anything you want 😄 - ideally via a Pull Request but don't worry, try it and we will work forward

**Comment by charlottebrf** [comment]
👍🏻

On Monday, 18 April 2016, Eddie Jaoude notifications@github.com wrote:

> Don't worry, its GitHub, everything is versioned, change anything you want
> 😄 - ideally via a Pull Request but don't worry, try it and we will work
> forward
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/WeRockTech/DiscussionTopics/issues/5#issuecomment-211501170

## 

---

_Charlotte Fereday_

Programmes Manager @codefirstgirls

Tweeting & retweeting @charlottebrf

*Mainly: Tech/Education/Hispanic studies *
