### ISSUE TITLE
CF: G Ones to Watch Discussion topics

### ISSUE THREAD

**Issue by charlottebrf** [WeRockTech/DiscussionTopics#7]
| Section | Details |
| --- | --- |
| CF: G Ones to Watch Discussion topics | formatting |
| Type | Other |
| Title | Formatting |
| Description | Apologies, but questions come out in block text not as separate bullet points in updated questions I added this morning. Let me know what I can do to correct formatting! |

![screen shot 2016-05-04 at 08 24 03](https://cloud.githubusercontent.com/assets/16884984/15007526/b4385e3a-11d1-11e6-964e-87cd83eee7c1.png)
                           |
| Screenshot  | Include? Yes / No                    |

**Comment by eddiejaoude** [comment]
You need a space after the formatter `#` or `*`.

From your commit:

#Intro

*Introduce yourself Can you tell us a bit more about what you do for a day job?

Raw:

```
#Intro

*Introduce yourself Can you tell us a bit more about what you do for a day job?
```

Needs to become

# Intro
- Introduce yourself Can you tell us a bit more about what you do for a day job?

Raw:

```
# Intro

* Introduce yourself Can you tell us a bit more about what you do for a day job?
```

**Comment by eddiejaoude** [comment]
PS. I hope you don't mind, I updated the formatting in the description of your ticket

**Comment by charlottebrf** [comment]
Thanks @eddiejaoude looks good

**Comment by eddiejaoude** [comment]
👍
